// lib/catalog/seed-catalog.ts
// Schema-shaped development catalog. Replace with Drizzle reads once staging
// DB is wired; keep ProductCardModel / CatalogProduct contracts stable.

import type { CatalogProduct } from "./types";

export const CATALOG_CATEGORIES = [
  { slug: "vapes", name: "Vapes" },
  { slug: "edibles", name: "Edibles" },
  { slug: "prerolls", name: "Prerolls" },
  { slug: "accessories", name: "Accessories" },
] as const;

export const CATALOG_LINES = [
  { slug: "signature", name: "Signature" },
  { slug: "live-reserve", name: "Live Reserve" },
  { slug: "balanced", name: "Balanced" },
  { slug: "rosin", name: "Rosin" },
  { slug: "state-exclusive", name: "State Exclusive" },
  { slug: "collabs", name: "Collabs" },
] as const;

export const SEED_CATALOG: CatalogProduct[] = [
  {
    id: "p-lr-gelato",
    slug: "live-reserve-gelato-1g",
    name: "Gelato Cartridge",
    description:
      "True-to-strain live resin profile with a dessert-forward finish. Lab-tested batch with published COA.",
    categorySlug: "vapes",
    categoryName: "Vapes",
    lineSlug: "live-reserve",
    lineName: "Live Reserve",
    strainType: "hybrid",
    status: "active",
    allowedJurisdictions: ["CA", "MA"],
    effects: ["relaxed", "euphoric", "creative"],
    coaUrl: "https://example.com/coa/live-reserve-gelato-1g",
    createdAt: "2026-05-01T00:00:00.000Z",
    popularityScore: 92,
    variants: [
      {
        id: "v-lr-gelato-1g",
        sku: "LR-GELATO-1G",
        weightOrFormat: "1g",
        retailPriceCents: 4500,
        thcPct: 82.5,
        cbdPct: 0.2,
        cbnPct: 0.1,
        quantityOnHand: 180,
      },
    ],
  },
  {
    id: "p-lr-og",
    slug: "live-reserve-og-kush-1g",
    name: "OG Kush Cartridge",
    description: "Classic Kush earth and pine in a liquid live resin cartridge.",
    categorySlug: "vapes",
    categoryName: "Vapes",
    lineSlug: "live-reserve",
    lineName: "Live Reserve",
    strainType: "indica",
    status: "active",
    allowedJurisdictions: ["CA", "MA"],
    effects: ["relaxed", "sleepy", "calm"],
    coaUrl: "https://example.com/coa/live-reserve-og-kush-1g",
    createdAt: "2026-05-04T00:00:00.000Z",
    popularityScore: 88,
    variants: [
      {
        id: "v-lr-og-1g",
        sku: "LR-OG-1G",
        weightOrFormat: "1g",
        retailPriceCents: 4500,
        thcPct: 79.8,
        cbdPct: 0.1,
        cbnPct: 0.4,
        quantityOnHand: 140,
      },
    ],
  },
  {
    id: "p-lr-sour",
    slug: "live-reserve-sour-diesel-1g",
    name: "Sour Diesel Cartridge",
    description: "Bright citrus-diesel profile for daytime sessions.",
    categorySlug: "vapes",
    categoryName: "Vapes",
    lineSlug: "live-reserve",
    lineName: "Live Reserve",
    strainType: "sativa",
    status: "active",
    allowedJurisdictions: ["CA", "MA"],
    effects: ["uplifted", "energetic", "focused"],
    coaUrl: "https://example.com/coa/live-reserve-sour-diesel-1g",
    createdAt: "2026-05-08T00:00:00.000Z",
    popularityScore: 85,
    variants: [
      {
        id: "v-lr-sour-1g",
        sku: "LR-SOUR-1G",
        weightOrFormat: "1g",
        retailPriceCents: 4500,
        thcPct: 84.1,
        cbdPct: 0.1,
        cbnPct: null,
        quantityOnHand: 96,
      },
    ],
  },
  {
    id: "p-sig-blue",
    slug: "signature-blue-dream-2g",
    name: "Blue Dream AIO",
    description: "All-in-one Signature device. Berry haze profile, USB-C rechargeable.",
    categorySlug: "vapes",
    categoryName: "Vapes",
    lineSlug: "signature",
    lineName: "Signature",
    strainType: "hybrid",
    status: "active",
    allowedJurisdictions: ["CA", "MA"],
    effects: ["uplifted", "creative", "happy"],
    coaUrl: "https://example.com/coa/signature-blue-dream-2g",
    createdAt: "2026-04-12T00:00:00.000Z",
    popularityScore: 97,
    variants: [
      {
        id: "v-sig-blue-2g",
        sku: "SIG-BD-2G",
        weightOrFormat: "2g",
        retailPriceCents: 6000,
        thcPct: 76.2,
        cbdPct: 0.3,
        cbnPct: 0.2,
        quantityOnHand: 210,
      },
      {
        id: "v-sig-blue-1g",
        sku: "SIG-BD-1G",
        weightOrFormat: "1g",
        retailPriceCents: 3800,
        thcPct: 75.4,
        cbdPct: 0.3,
        cbnPct: 0.2,
        quantityOnHand: 160,
      },
    ],
  },
  {
    id: "p-sig-wedding",
    slug: "signature-wedding-cake-1g",
    name: "Wedding Cake AIO",
    description: "Vanilla-frosting sweetness with a dense, calm finish.",
    categorySlug: "vapes",
    categoryName: "Vapes",
    lineSlug: "signature",
    lineName: "Signature",
    strainType: "hybrid",
    status: "active",
    allowedJurisdictions: ["CA", "MA"],
    effects: ["relaxed", "happy", "euphoric"],
    coaUrl: "https://example.com/coa/signature-wedding-cake-1g",
    createdAt: "2026-04-20T00:00:00.000Z",
    popularityScore: 90,
    variants: [
      {
        id: "v-sig-wc-1g",
        sku: "SIG-WC-1G",
        weightOrFormat: "1g",
        retailPriceCents: 3800,
        thcPct: 78.9,
        cbdPct: 0.2,
        cbnPct: 0.3,
        quantityOnHand: 175,
      },
    ],
  },
  {
    id: "p-sig-strawberry",
    slug: "signature-strawberry-cough-aio-1g",
    name: "Strawberry Cough AIO",
    description: "Sweet strawberry with a skunky backbone. Signature all-in-one.",
    categorySlug: "vapes",
    categoryName: "Vapes",
    lineSlug: "signature",
    lineName: "Signature",
    strainType: "sativa",
    status: "active",
    allowedJurisdictions: ["CA", "MA"],
    effects: ["uplifted", "euphoric", "energetic", "creative", "focused"],
    coaUrl: "https://example.com/coa/signature-strawberry-cough-aio-1g",
    createdAt: "2026-06-01T00:00:00.000Z",
    popularityScore: 94,
    variants: [
      {
        id: "v-sig-sc-1g",
        sku: "SIG-SC-1G",
        weightOrFormat: "1g",
        retailPriceCents: 4000,
        thcPct: 81.0,
        cbdPct: 0.2,
        cbnPct: null,
        quantityOnHand: 200,
      },
    ],
  },
  {
    id: "p-rosin-peach",
    slug: "rosin-peach-kush-1g",
    name: "Peach Kush Rosin Cart",
    description: "Solventless-forward peach and kush profile for connoisseurs.",
    categorySlug: "vapes",
    categoryName: "Vapes",
    lineSlug: "rosin",
    lineName: "Rosin",
    strainType: "indica",
    status: "active",
    allowedJurisdictions: ["CA"],
    effects: ["relaxed", "calm"],
    coaUrl: "https://example.com/coa/rosin-peach-kush-1g",
    createdAt: "2026-06-10T00:00:00.000Z",
    popularityScore: 70,
    variants: [
      {
        id: "v-rosin-pk-1g",
        sku: "ROS-PK-1G",
        weightOrFormat: "1g",
        retailPriceCents: 6500,
        thcPct: 71.2,
        cbdPct: 0.4,
        cbnPct: 0.5,
        quantityOnHand: 48,
      },
    ],
  },
  {
    id: "p-bal-gummy",
    slug: "balanced-citrus-gummies-10pk",
    name: "Citrus Balanced Gummies",
    description: "10-pack balanced THC:CBD soft chews for measured sessions.",
    categorySlug: "edibles",
    categoryName: "Edibles",
    lineSlug: "balanced",
    lineName: "Balanced",
    strainType: "hybrid",
    status: "active",
    allowedJurisdictions: ["CA", "MA"],
    effects: ["calm", "balanced"],
    coaUrl: "https://example.com/coa/balanced-citrus-gummies-10pk",
    createdAt: "2026-03-15T00:00:00.000Z",
    popularityScore: 80,
    variants: [
      {
        id: "v-bal-gummy-10",
        sku: "BAL-CIT-10PK",
        weightOrFormat: "10pk",
        retailPriceCents: 2800,
        thcPct: 10.0,
        cbdPct: 10.0,
        cbnPct: null,
        quantityOnHand: 320,
      },
    ],
  },
  {
    id: "p-bal-softgel",
    slug: "balanced-softgels-30ct",
    name: "Balanced Softgels",
    description: "30-count softgels with a 1:1 THC:CBD ratio.",
    categorySlug: "edibles",
    categoryName: "Edibles",
    lineSlug: "balanced",
    lineName: "Balanced",
    strainType: "hybrid",
    status: "active",
    allowedJurisdictions: ["CA", "MA"],
    effects: ["calm", "focused"],
    coaUrl: "https://example.com/coa/balanced-softgels-30ct",
    createdAt: "2026-03-22T00:00:00.000Z",
    popularityScore: 74,
    variants: [
      {
        id: "v-bal-sg-30",
        sku: "BAL-SG-30",
        weightOrFormat: "30ct",
        retailPriceCents: 4200,
        thcPct: 5.0,
        cbdPct: 5.0,
        cbnPct: null,
        quantityOnHand: 150,
      },
    ],
  },
  {
    id: "p-preroll-littles",
    slug: "little-ds-preroll-5pk",
    name: "Little D's Pre-Rolls",
    description: "Five-pack of evenly packed prerolls from the Signature leaf.",
    categorySlug: "prerolls",
    categoryName: "Prerolls",
    lineSlug: "signature",
    lineName: "Signature",
    strainType: "hybrid",
    status: "active",
    allowedJurisdictions: ["CA", "MA"],
    effects: ["happy", "social"],
    coaUrl: "https://example.com/coa/little-ds-preroll-5pk",
    createdAt: "2026-02-28T00:00:00.000Z",
    popularityScore: 78,
    variants: [
      {
        id: "v-pr-5pk",
        sku: "SIG-LD-5PK",
        weightOrFormat: "5pk",
        retailPriceCents: 3500,
        thcPct: 22.4,
        cbdPct: 0.2,
        cbnPct: 0.1,
        quantityOnHand: 260,
      },
    ],
  },
  {
    id: "p-acc-battery",
    slug: "signature-510-battery",
    name: "Signature 510 Battery",
    description: "Button-activated 510 battery with multi-voltage heat settings.",
    categorySlug: "accessories",
    categoryName: "Accessories",
    lineSlug: "signature",
    lineName: "Signature",
    strainType: "na",
    status: "active",
    allowedJurisdictions: ["CA", "MA"],
    effects: [],
    coaUrl: null,
    createdAt: "2026-01-10T00:00:00.000Z",
    popularityScore: 66,
    variants: [
      {
        id: "v-bat-510",
        sku: "SIG-BAT-510",
        weightOrFormat: "1 each",
        retailPriceCents: 2500,
        thcPct: 0,
        cbdPct: 0,
        cbnPct: null,
        quantityOnHand: 400,
      },
    ],
  },
  {
    id: "p-state-ma",
    slug: "state-exclusive-jet-fuel-1g",
    name: "Jet Fuel Live Resin Disposable",
    description: "Massachusetts state-exclusive live resin disposable.",
    categorySlug: "vapes",
    categoryName: "Vapes",
    lineSlug: "state-exclusive",
    lineName: "State Exclusive",
    strainType: "sativa",
    status: "active",
    allowedJurisdictions: ["MA"],
    effects: ["energetic", "focused"],
    coaUrl: "https://example.com/coa/state-exclusive-jet-fuel-1g",
    createdAt: "2026-06-18T00:00:00.000Z",
    popularityScore: 72,
    variants: [
      {
        id: "v-se-jf-1g",
        sku: "SE-JF-1G-MA",
        weightOrFormat: "1g",
        retailPriceCents: 6500,
        thcPct: 91.5,
        cbdPct: 0.1,
        cbnPct: null,
        quantityOnHand: 55,
      },
    ],
  },
];
