// lib/checkout/subdivisions.ts
import { US_STATES } from "@/lib/checkout/tax-rates";

export type Subdivision = { code: string; name: string };

const CA_PROVINCES: Subdivision[] = [
  { code: "AB", name: "Alberta" },
  { code: "BC", name: "British Columbia" },
  { code: "MB", name: "Manitoba" },
  { code: "NB", name: "New Brunswick" },
  { code: "NL", name: "Newfoundland and Labrador" },
  { code: "NS", name: "Nova Scotia" },
  { code: "NT", name: "Northwest Territories" },
  { code: "NU", name: "Nunavut" },
  { code: "ON", name: "Ontario" },
  { code: "PE", name: "Prince Edward Island" },
  { code: "QC", name: "Quebec" },
  { code: "SK", name: "Saskatchewan" },
  { code: "YT", name: "Yukon" },
];

const AU_STATES: Subdivision[] = [
  { code: "ACT", name: "Australian Capital Territory" },
  { code: "NSW", name: "New South Wales" },
  { code: "NT", name: "Northern Territory" },
  { code: "QLD", name: "Queensland" },
  { code: "SA", name: "South Australia" },
  { code: "TAS", name: "Tasmania" },
  { code: "VIC", name: "Victoria" },
  { code: "WA", name: "Western Australia" },
];

const GB_REGIONS: Subdivision[] = [
  { code: "ENG", name: "England" },
  { code: "SCT", name: "Scotland" },
  { code: "WLS", name: "Wales" },
  { code: "NIR", name: "Northern Ireland" },
];

const MX_STATES: Subdivision[] = [
  { code: "AGU", name: "Aguascalientes" },
  { code: "BCN", name: "Baja California" },
  { code: "BCS", name: "Baja California Sur" },
  { code: "CAM", name: "Campeche" },
  { code: "CHP", name: "Chiapas" },
  { code: "CHH", name: "Chihuahua" },
  { code: "CMX", name: "Ciudad de México" },
  { code: "COA", name: "Coahuila" },
  { code: "COL", name: "Colima" },
  { code: "DUR", name: "Durango" },
  { code: "GUA", name: "Guanajuato" },
  { code: "GRO", name: "Guerrero" },
  { code: "HID", name: "Hidalgo" },
  { code: "JAL", name: "Jalisco" },
  { code: "MEX", name: "México" },
  { code: "MIC", name: "Michoacán" },
  { code: "MOR", name: "Morelos" },
  { code: "NAY", name: "Nayarit" },
  { code: "NLE", name: "Nuevo León" },
  { code: "OAX", name: "Oaxaca" },
  { code: "PUE", name: "Puebla" },
  { code: "QUE", name: "Querétaro" },
  { code: "ROO", name: "Quintana Roo" },
  { code: "SLP", name: "San Luis Potosí" },
  { code: "SIN", name: "Sinaloa" },
  { code: "SON", name: "Sonora" },
  { code: "TAB", name: "Tabasco" },
  { code: "TAM", name: "Tamaulipas" },
  { code: "TLA", name: "Tlaxcala" },
  { code: "VER", name: "Veracruz" },
  { code: "YUC", name: "Yucatán" },
  { code: "ZAC", name: "Zacatecas" },
];

const BR_STATES: Subdivision[] = [
  { code: "AC", name: "Acre" },
  { code: "AL", name: "Alagoas" },
  { code: "AP", name: "Amapá" },
  { code: "AM", name: "Amazonas" },
  { code: "BA", name: "Bahia" },
  { code: "CE", name: "Ceará" },
  { code: "DF", name: "Distrito Federal" },
  { code: "ES", name: "Espírito Santo" },
  { code: "GO", name: "Goiás" },
  { code: "MA", name: "Maranhão" },
  { code: "MT", name: "Mato Grosso" },
  { code: "MS", name: "Mato Grosso do Sul" },
  { code: "MG", name: "Minas Gerais" },
  { code: "PA", name: "Pará" },
  { code: "PB", name: "Paraíba" },
  { code: "PR", name: "Paraná" },
  { code: "PE", name: "Pernambuco" },
  { code: "PI", name: "Piauí" },
  { code: "RJ", name: "Rio de Janeiro" },
  { code: "RN", name: "Rio Grande do Norte" },
  { code: "RS", name: "Rio Grande do Sul" },
  { code: "RO", name: "Rondônia" },
  { code: "RR", name: "Roraima" },
  { code: "SC", name: "Santa Catarina" },
  { code: "SP", name: "São Paulo" },
  { code: "SE", name: "Sergipe" },
  { code: "TO", name: "Tocantins" },
];

const IN_STATES: Subdivision[] = [
  { code: "AN", name: "Andaman and Nicobar Islands" },
  { code: "AP", name: "Andhra Pradesh" },
  { code: "AR", name: "Arunachal Pradesh" },
  { code: "AS", name: "Assam" },
  { code: "BR", name: "Bihar" },
  { code: "CH", name: "Chandigarh" },
  { code: "CT", name: "Chhattisgarh" },
  { code: "DH", name: "Dadra and Nagar Haveli and Daman and Diu" },
  { code: "DL", name: "Delhi" },
  { code: "GA", name: "Goa" },
  { code: "GJ", name: "Gujarat" },
  { code: "HR", name: "Haryana" },
  { code: "HP", name: "Himachal Pradesh" },
  { code: "JK", name: "Jammu and Kashmir" },
  { code: "JH", name: "Jharkhand" },
  { code: "KA", name: "Karnataka" },
  { code: "KL", name: "Kerala" },
  { code: "LA", name: "Ladakh" },
  { code: "LD", name: "Lakshadweep" },
  { code: "MP", name: "Madhya Pradesh" },
  { code: "MH", name: "Maharashtra" },
  { code: "MN", name: "Manipur" },
  { code: "ML", name: "Meghalaya" },
  { code: "MZ", name: "Mizoram" },
  { code: "NL", name: "Nagaland" },
  { code: "OD", name: "Odisha" },
  { code: "PY", name: "Puducherry" },
  { code: "PB", name: "Punjab" },
  { code: "RJ", name: "Rajasthan" },
  { code: "SK", name: "Sikkim" },
  { code: "TN", name: "Tamil Nadu" },
  { code: "TS", name: "Telangana" },
  { code: "TR", name: "Tripura" },
  { code: "UP", name: "Uttar Pradesh" },
  { code: "UK", name: "Uttarakhand" },
  { code: "WB", name: "West Bengal" },
];

const DE_STATES: Subdivision[] = [
  { code: "BW", name: "Baden-Württemberg" },
  { code: "BY", name: "Bavaria" },
  { code: "BE", name: "Berlin" },
  { code: "BB", name: "Brandenburg" },
  { code: "HB", name: "Bremen" },
  { code: "HH", name: "Hamburg" },
  { code: "HE", name: "Hesse" },
  { code: "MV", name: "Mecklenburg-Vorpommern" },
  { code: "NI", name: "Lower Saxony" },
  { code: "NW", name: "North Rhine-Westphalia" },
  { code: "RP", name: "Rhineland-Palatinate" },
  { code: "SL", name: "Saarland" },
  { code: "SN", name: "Saxony" },
  { code: "ST", name: "Saxony-Anhalt" },
  { code: "SH", name: "Schleswig-Holstein" },
  { code: "TH", name: "Thuringia" },
];

const JP_PREFECTURES: Subdivision[] = [
  { code: "Hokkaido", name: "Hokkaido" },
  { code: "Aomori", name: "Aomori" },
  { code: "Iwate", name: "Iwate" },
  { code: "Miyagi", name: "Miyagi" },
  { code: "Akita", name: "Akita" },
  { code: "Yamagata", name: "Yamagata" },
  { code: "Fukushima", name: "Fukushima" },
  { code: "Ibaraki", name: "Ibaraki" },
  { code: "Tochigi", name: "Tochigi" },
  { code: "Gunma", name: "Gunma" },
  { code: "Saitama", name: "Saitama" },
  { code: "Chiba", name: "Chiba" },
  { code: "Tokyo", name: "Tokyo" },
  { code: "Kanagawa", name: "Kanagawa" },
  { code: "Niigata", name: "Niigata" },
  { code: "Toyama", name: "Toyama" },
  { code: "Ishikawa", name: "Ishikawa" },
  { code: "Fukui", name: "Fukui" },
  { code: "Yamanashi", name: "Yamanashi" },
  { code: "Nagano", name: "Nagano" },
  { code: "Gifu", name: "Gifu" },
  { code: "Shizuoka", name: "Shizuoka" },
  { code: "Aichi", name: "Aichi" },
  { code: "Mie", name: "Mie" },
  { code: "Shiga", name: "Shiga" },
  { code: "Kyoto", name: "Kyoto" },
  { code: "Osaka", name: "Osaka" },
  { code: "Hyogo", name: "Hyogo" },
  { code: "Nara", name: "Nara" },
  { code: "Wakayama", name: "Wakayama" },
  { code: "Tottori", name: "Tottori" },
  { code: "Shimane", name: "Shimane" },
  { code: "Okayama", name: "Okayama" },
  { code: "Hiroshima", name: "Hiroshima" },
  { code: "Yamaguchi", name: "Yamaguchi" },
  { code: "Tokushima", name: "Tokushima" },
  { code: "Kagawa", name: "Kagawa" },
  { code: "Ehime", name: "Ehime" },
  { code: "Kochi", name: "Kochi" },
  { code: "Fukuoka", name: "Fukuoka" },
  { code: "Saga", name: "Saga" },
  { code: "Nagasaki", name: "Nagasaki" },
  { code: "Kumamoto", name: "Kumamoto" },
  { code: "Oita", name: "Oita" },
  { code: "Miyazaki", name: "Miyazaki" },
  { code: "Kagoshima", name: "Kagoshima" },
  { code: "Okinawa", name: "Okinawa" },
];

const NZ_REGIONS: Subdivision[] = [
  { code: "AUK", name: "Auckland" },
  { code: "BOP", name: "Bay of Plenty" },
  { code: "CAN", name: "Canterbury" },
  { code: "GIS", name: "Gisborne" },
  { code: "HKB", name: "Hawke's Bay" },
  { code: "MWT", name: "Manawatū-Whanganui" },
  { code: "MBH", name: "Marlborough" },
  { code: "NSN", name: "Nelson" },
  { code: "NTL", name: "Northland" },
  { code: "OTA", name: "Otago" },
  { code: "STL", name: "Southland" },
  { code: "TKI", name: "Taranaki" },
  { code: "TAS", name: "Tasman" },
  { code: "WKO", name: "Waikato" },
  { code: "WGN", name: "Wellington" },
  { code: "WTC", name: "West Coast" },
];

const IE_COUNTIES: Subdivision[] = [
  { code: "CW", name: "Carlow" },
  { code: "CN", name: "Cavan" },
  { code: "CE", name: "Clare" },
  { code: "CO", name: "Cork" },
  { code: "DL", name: "Donegal" },
  { code: "D", name: "Dublin" },
  { code: "G", name: "Galway" },
  { code: "KY", name: "Kerry" },
  { code: "KE", name: "Kildare" },
  { code: "KK", name: "Kilkenny" },
  { code: "LS", name: "Laois" },
  { code: "LM", name: "Leitrim" },
  { code: "LK", name: "Limerick" },
  { code: "LD", name: "Longford" },
  { code: "LH", name: "Louth" },
  { code: "MO", name: "Mayo" },
  { code: "MH", name: "Meath" },
  { code: "MN", name: "Monaghan" },
  { code: "OY", name: "Offaly" },
  { code: "RN", name: "Roscommon" },
  { code: "SO", name: "Sligo" },
  { code: "TA", name: "Tipperary" },
  { code: "WD", name: "Waterford" },
  { code: "WH", name: "Westmeath" },
  { code: "WX", name: "Wexford" },
  { code: "WW", name: "Wicklow" },
];

const ZA_PROVINCES: Subdivision[] = [
  { code: "EC", name: "Eastern Cape" },
  { code: "FS", name: "Free State" },
  { code: "GP", name: "Gauteng" },
  { code: "KZN", name: "KwaZulu-Natal" },
  { code: "LP", name: "Limpopo" },
  { code: "MP", name: "Mpumalanga" },
  { code: "NC", name: "Northern Cape" },
  { code: "NW", name: "North West" },
  { code: "WC", name: "Western Cape" },
];

const PH_REGIONS: Subdivision[] = [
  { code: "NCR", name: "National Capital Region" },
  { code: "CAR", name: "Cordillera Administrative Region" },
  { code: "I", name: "Ilocos Region" },
  { code: "II", name: "Cagayan Valley" },
  { code: "III", name: "Central Luzon" },
  { code: "IV-A", name: "Calabarzon" },
  { code: "MIMAROPA", name: "Mimaropa" },
  { code: "V", name: "Bicol Region" },
  { code: "VI", name: "Western Visayas" },
  { code: "VII", name: "Central Visayas" },
  { code: "VIII", name: "Eastern Visayas" },
  { code: "IX", name: "Zamboanga Peninsula" },
  { code: "X", name: "Northern Mindanao" },
  { code: "XI", name: "Davao Region" },
  { code: "XII", name: "Soccsksargen" },
  { code: "XIII", name: "Caraga" },
  { code: "BARMM", name: "Bangsamoro" },
];

const ES_REGIONS: Subdivision[] = [
  { code: "AN", name: "Andalusia" },
  { code: "AR", name: "Aragon" },
  { code: "AS", name: "Asturias" },
  { code: "IB", name: "Balearic Islands" },
  { code: "PV", name: "Basque Country" },
  { code: "CN", name: "Canary Islands" },
  { code: "CB", name: "Cantabria" },
  { code: "CL", name: "Castile and León" },
  { code: "CM", name: "Castile-La Mancha" },
  { code: "CT", name: "Catalonia" },
  { code: "EX", name: "Extremadura" },
  { code: "GA", name: "Galicia" },
  { code: "MD", name: "Madrid" },
  { code: "MC", name: "Murcia" },
  { code: "NC", name: "Navarre" },
  { code: "RI", name: "La Rioja" },
  { code: "VC", name: "Valencian Community" },
  { code: "CE", name: "Ceuta" },
  { code: "ML", name: "Melilla" },
];

const IT_REGIONS: Subdivision[] = [
  { code: "Abruzzo", name: "Abruzzo" },
  { code: "Basilicata", name: "Basilicata" },
  { code: "Calabria", name: "Calabria" },
  { code: "Campania", name: "Campania" },
  { code: "Emilia-Romagna", name: "Emilia-Romagna" },
  { code: "Friuli-Venezia Giulia", name: "Friuli-Venezia Giulia" },
  { code: "Lazio", name: "Lazio" },
  { code: "Liguria", name: "Liguria" },
  { code: "Lombardia", name: "Lombardia" },
  { code: "Marche", name: "Marche" },
  { code: "Molise", name: "Molise" },
  { code: "Piemonte", name: "Piemonte" },
  { code: "Puglia", name: "Puglia" },
  { code: "Sardegna", name: "Sardegna" },
  { code: "Sicilia", name: "Sicilia" },
  { code: "Toscana", name: "Toscana" },
  { code: "Trentino-Alto Adige", name: "Trentino-Alto Adige" },
  { code: "Umbria", name: "Umbria" },
  { code: "Valle d'Aosta", name: "Valle d'Aosta" },
  { code: "Veneto", name: "Veneto" },
];

const FR_REGIONS: Subdivision[] = [
  { code: "ARA", name: "Auvergne-Rhône-Alpes" },
  { code: "BFC", name: "Bourgogne-Franche-Comté" },
  { code: "BRE", name: "Brittany" },
  { code: "CVL", name: "Centre-Val de Loire" },
  { code: "COR", name: "Corsica" },
  { code: "GES", name: "Grand Est" },
  { code: "HDF", name: "Hauts-de-France" },
  { code: "IDF", name: "Île-de-France" },
  { code: "NOR", name: "Normandy" },
  { code: "NAQ", name: "Nouvelle-Aquitaine" },
  { code: "OCC", name: "Occitanie" },
  { code: "PDL", name: "Pays de la Loire" },
  { code: "PAC", name: "Provence-Alpes-Côte d'Azur" },
  { code: "GUA", name: "Guadeloupe" },
  { code: "GUF", name: "French Guiana" },
  { code: "MTQ", name: "Martinique" },
  { code: "REU", name: "Réunion" },
  { code: "MAY", name: "Mayotte" },
];

const NL_PROVINCES: Subdivision[] = [
  { code: "DR", name: "Drenthe" },
  { code: "FL", name: "Flevoland" },
  { code: "FR", name: "Friesland" },
  { code: "GE", name: "Gelderland" },
  { code: "GR", name: "Groningen" },
  { code: "LI", name: "Limburg" },
  { code: "NB", name: "North Brabant" },
  { code: "NH", name: "North Holland" },
  { code: "OV", name: "Overijssel" },
  { code: "UT", name: "Utrecht" },
  { code: "ZE", name: "Zeeland" },
  { code: "ZH", name: "South Holland" },
];

const BE_REGIONS: Subdivision[] = [
  { code: "BRU", name: "Brussels" },
  { code: "VLG", name: "Flanders" },
  { code: "WAL", name: "Wallonia" },
];

const CH_CANTONS: Subdivision[] = [
  { code: "AG", name: "Aargau" },
  { code: "AI", name: "Appenzell Innerrhoden" },
  { code: "AR", name: "Appenzell Ausserrhoden" },
  { code: "BE", name: "Bern" },
  { code: "BL", name: "Basel-Landschaft" },
  { code: "BS", name: "Basel-Stadt" },
  { code: "FR", name: "Fribourg" },
  { code: "GE", name: "Geneva" },
  { code: "GL", name: "Glarus" },
  { code: "GR", name: "Graubünden" },
  { code: "JU", name: "Jura" },
  { code: "LU", name: "Lucerne" },
  { code: "NE", name: "Neuchâtel" },
  { code: "NW", name: "Nidwalden" },
  { code: "OW", name: "Obwalden" },
  { code: "SG", name: "St. Gallen" },
  { code: "SH", name: "Schaffhausen" },
  { code: "SO", name: "Solothurn" },
  { code: "SZ", name: "Schwyz" },
  { code: "TG", name: "Thurgau" },
  { code: "TI", name: "Ticino" },
  { code: "UR", name: "Uri" },
  { code: "VD", name: "Vaud" },
  { code: "VS", name: "Valais" },
  { code: "ZG", name: "Zug" },
  { code: "ZH", name: "Zurich" },
];

const AT_STATES: Subdivision[] = [
  { code: "B", name: "Burgenland" },
  { code: "K", name: "Carinthia" },
  { code: "Noe", name: "Lower Austria" },
  { code: "Ooe", name: "Upper Austria" },
  { code: "S", name: "Salzburg" },
  { code: "St", name: "Styria" },
  { code: "T", name: "Tyrol" },
  { code: "V", name: "Vorarlberg" },
  { code: "W", name: "Vienna" },
];

const AR_PROVINCES: Subdivision[] = [
  { code: "B", name: "Buenos Aires" },
  { code: "C", name: "Ciudad Autónoma de Buenos Aires" },
  { code: "K", name: "Catamarca" },
  { code: "H", name: "Chaco" },
  { code: "U", name: "Chubut" },
  { code: "X", name: "Córdoba" },
  { code: "W", name: "Corrientes" },
  { code: "E", name: "Entre Ríos" },
  { code: "P", name: "Formosa" },
  { code: "Y", name: "Jujuy" },
  { code: "L", name: "La Pampa" },
  { code: "F", name: "La Rioja" },
  { code: "M", name: "Mendoza" },
  { code: "N", name: "Misiones" },
  { code: "Q", name: "Neuquén" },
  { code: "R", name: "Río Negro" },
  { code: "A", name: "Salta" },
  { code: "J", name: "San Juan" },
  { code: "D", name: "San Luis" },
  { code: "Z", name: "Santa Cruz" },
  { code: "S", name: "Santa Fe" },
  { code: "G", name: "Santiago del Estero" },
  { code: "V", name: "Tierra del Fuego" },
  { code: "T", name: "Tucumán" },
];

const CL_REGIONS: Subdivision[] = [
  { code: "AI", name: "Aysén" },
  { code: "AN", name: "Antofagasta" },
  { code: "AP", name: "Arica y Parinacota" },
  { code: "AR", name: "Araucanía" },
  { code: "AT", name: "Atacama" },
  { code: "BI", name: "Biobío" },
  { code: "CO", name: "Coquimbo" },
  { code: "LI", name: "O'Higgins" },
  { code: "LL", name: "Los Lagos" },
  { code: "LR", name: "Los Ríos" },
  { code: "MA", name: "Magallanes" },
  { code: "ML", name: "Maule" },
  { code: "NB", name: "Ñuble" },
  { code: "RM", name: "Santiago Metropolitan" },
  { code: "TA", name: "Tarapacá" },
  { code: "VS", name: "Valparaíso" },
];

const CO_DEPARTMENTS: Subdivision[] = [
  { code: "AMA", name: "Amazonas" },
  { code: "ANT", name: "Antioquia" },
  { code: "ARA", name: "Arauca" },
  { code: "ATL", name: "Atlántico" },
  { code: "BOL", name: "Bolívar" },
  { code: "BOY", name: "Boyacá" },
  { code: "CAL", name: "Caldas" },
  { code: "CAQ", name: "Caquetá" },
  { code: "CAS", name: "Casanare" },
  { code: "CAU", name: "Cauca" },
  { code: "CES", name: "Cesar" },
  { code: "CHO", name: "Chocó" },
  { code: "COR", name: "Córdoba" },
  { code: "CUN", name: "Cundinamarca" },
  { code: "DC", name: "Bogotá D.C." },
  { code: "GUA", name: "Guainía" },
  { code: "GUV", name: "Guaviare" },
  { code: "HUI", name: "Huila" },
  { code: "LAG", name: "La Guajira" },
  { code: "MAG", name: "Magdalena" },
  { code: "MET", name: "Meta" },
  { code: "NAR", name: "Nariño" },
  { code: "NSA", name: "Norte de Santander" },
  { code: "PUT", name: "Putumayo" },
  { code: "QUI", name: "Quindío" },
  { code: "RIS", name: "Risaralda" },
  { code: "SAP", name: "San Andrés y Providencia" },
  { code: "SAN", name: "Santander" },
  { code: "SUC", name: "Sucre" },
  { code: "TOL", name: "Tolima" },
  { code: "VAC", name: "Valle del Cauca" },
  { code: "VAU", name: "Vaupés" },
  { code: "VID", name: "Vichada" },
];

const AE_EMIRATES: Subdivision[] = [
  { code: "AZ", name: "Abu Dhabi" },
  { code: "AJ", name: "Ajman" },
  { code: "DU", name: "Dubai" },
  { code: "FU", name: "Fujairah" },
  { code: "RK", name: "Ras Al Khaimah" },
  { code: "SH", name: "Sharjah" },
  { code: "UQ", name: "Umm Al Quwain" },
];

const KR_REGIONS: Subdivision[] = [
  { code: "Seoul", name: "Seoul" },
  { code: "Busan", name: "Busan" },
  { code: "Daegu", name: "Daegu" },
  { code: "Incheon", name: "Incheon" },
  { code: "Gwangju", name: "Gwangju" },
  { code: "Daejeon", name: "Daejeon" },
  { code: "Ulsan", name: "Ulsan" },
  { code: "Sejong", name: "Sejong" },
  { code: "Gyeonggi", name: "Gyeonggi" },
  { code: "Gangwon", name: "Gangwon" },
  { code: "North Chungcheong", name: "North Chungcheong" },
  { code: "South Chungcheong", name: "South Chungcheong" },
  { code: "North Jeolla", name: "North Jeolla" },
  { code: "South Jeolla", name: "South Jeolla" },
  { code: "North Gyeongsang", name: "North Gyeongsang" },
  { code: "South Gyeongsang", name: "South Gyeongsang" },
  { code: "Jeju", name: "Jeju" },
];

const MY_STATES: Subdivision[] = [
  { code: "JHR", name: "Johor" },
  { code: "KDH", name: "Kedah" },
  { code: "KTN", name: "Kelantan" },
  { code: "MLK", name: "Malacca" },
  { code: "NSN", name: "Negeri Sembilan" },
  { code: "PHG", name: "Pahang" },
  { code: "PNG", name: "Penang" },
  { code: "PRK", name: "Perak" },
  { code: "PLS", name: "Perlis" },
  { code: "SBH", name: "Sabah" },
  { code: "SWK", name: "Sarawak" },
  { code: "SGR", name: "Selangor" },
  { code: "TRG", name: "Terengganu" },
  { code: "KUL", name: "Kuala Lumpur" },
  { code: "LBN", name: "Labuan" },
  { code: "PJY", name: "Putrajaya" },
];

const TH_REGIONS: Subdivision[] = [
  { code: "Bangkok", name: "Bangkok" },
  { code: "Central", name: "Central" },
  { code: "Eastern", name: "Eastern" },
  { code: "Northeastern", name: "Northeastern" },
  { code: "Northern", name: "Northern" },
  { code: "Southern", name: "Southern" },
  { code: "Western", name: "Western" },
];

const ID_PROVINCES: Subdivision[] = [
  { code: "AC", name: "Aceh" },
  { code: "BA", name: "Bali" },
  { code: "BB", name: "Bangka Belitung" },
  { code: "BT", name: "Banten" },
  { code: "BE", name: "Bengkulu" },
  { code: "JT", name: "Central Java" },
  { code: "KT", name: "Central Kalimantan" },
  { code: "ST", name: "Central Sulawesi" },
  { code: "JI", name: "East Java" },
  { code: "KI", name: "East Kalimantan" },
  { code: "NT", name: "East Nusa Tenggara" },
  { code: "GO", name: "Gorontalo" },
  { code: "JK", name: "Jakarta" },
  { code: "JA", name: "Jambi" },
  { code: "LA", name: "Lampung" },
  { code: "MA", name: "Maluku" },
  { code: "MU", name: "North Maluku" },
  { code: "SA", name: "North Sulawesi" },
  { code: "SU", name: "North Sumatra" },
  { code: "PA", name: "Papua" },
  { code: "RI", name: "Riau" },
  { code: "KR", name: "Riau Islands" },
  { code: "SS", name: "South Sumatra" },
  { code: "SN", name: "South Sulawesi" },
  { code: "KS", name: "South Kalimantan" },
  { code: "SG", name: "Southeast Sulawesi" },
  { code: "JB", name: "West Java" },
  { code: "KB", name: "West Kalimantan" },
  { code: "NB", name: "West Nusa Tenggara" },
  { code: "PB", name: "West Papua" },
  { code: "SR", name: "West Sulawesi" },
  { code: "SB", name: "West Sumatra" },
  { code: "YO", name: "Yogyakarta" },
];

const PT_DISTRICTS: Subdivision[] = [
  { code: "Aveiro", name: "Aveiro" },
  { code: "Beja", name: "Beja" },
  { code: "Braga", name: "Braga" },
  { code: "Bragança", name: "Bragança" },
  { code: "Castelo Branco", name: "Castelo Branco" },
  { code: "Coimbra", name: "Coimbra" },
  { code: "Évora", name: "Évora" },
  { code: "Faro", name: "Faro" },
  { code: "Guarda", name: "Guarda" },
  { code: "Leiria", name: "Leiria" },
  { code: "Lisboa", name: "Lisboa" },
  { code: "Portalegre", name: "Portalegre" },
  { code: "Porto", name: "Porto" },
  { code: "Santarém", name: "Santarém" },
  { code: "Setúbal", name: "Setúbal" },
  { code: "Viana do Castelo", name: "Viana do Castelo" },
  { code: "Vila Real", name: "Vila Real" },
  { code: "Viseu", name: "Viseu" },
  { code: "Azores", name: "Azores" },
  { code: "Madeira", name: "Madeira" },
];

const PL_VOIVODESHIPS: Subdivision[] = [
  { code: "DS", name: "Lower Silesian" },
  { code: "KP", name: "Kuyavian-Pomeranian" },
  { code: "LU", name: "Lublin" },
  { code: "LB", name: "Lubusz" },
  { code: "LD", name: "Łódź" },
  { code: "MA", name: "Lesser Poland" },
  { code: "MZ", name: "Masovian" },
  { code: "OP", name: "Opole" },
  { code: "PK", name: "Subcarpathian" },
  { code: "PD", name: "Podlaskie" },
  { code: "PM", name: "Pomeranian" },
  { code: "SL", name: "Silesian" },
  { code: "SK", name: "Holy Cross" },
  { code: "WN", name: "Warmian-Masurian" },
  { code: "WP", name: "Greater Poland" },
  { code: "ZP", name: "West Pomeranian" },
];

const SE_COUNTIES: Subdivision[] = [
  { code: "AB", name: "Stockholm" },
  { code: "AC", name: "Västerbotten" },
  { code: "BD", name: "Norrbotten" },
  { code: "C", name: "Uppsala" },
  { code: "D", name: "Södermanland" },
  { code: "E", name: "Östergötland" },
  { code: "F", name: "Jönköping" },
  { code: "G", name: "Kronoberg" },
  { code: "H", name: "Kalmar" },
  { code: "I", name: "Gotland" },
  { code: "K", name: "Blekinge" },
  { code: "M", name: "Skåne" },
  { code: "N", name: "Halland" },
  { code: "O", name: "Västra Götaland" },
  { code: "S", name: "Värmland" },
  { code: "T", name: "Örebro" },
  { code: "U", name: "Västmanland" },
  { code: "W", name: "Dalarna" },
  { code: "X", name: "Gävleborg" },
  { code: "Y", name: "Västernorrland" },
  { code: "Z", name: "Jämtland" },
];

const NO_COUNTIES: Subdivision[] = [
  { code: "03", name: "Oslo" },
  { code: "11", name: "Rogaland" },
  { code: "15", name: "Møre og Romsdal" },
  { code: "18", name: "Nordland" },
  { code: "30", name: "Viken" },
  { code: "34", name: "Innlandet" },
  { code: "38", name: "Vestfold og Telemark" },
  { code: "42", name: "Agder" },
  { code: "46", name: "Vestland" },
  { code: "50", name: "Trøndelag" },
  { code: "54", name: "Troms og Finnmark" },
];

const DK_REGIONS: Subdivision[] = [
  { code: "84", name: "Capital Region" },
  { code: "82", name: "Central Denmark" },
  { code: "81", name: "North Denmark" },
  { code: "85", name: "Zealand" },
  { code: "83", name: "Southern Denmark" },
];

const FI_REGIONS: Subdivision[] = [
  { code: "01", name: "Åland" },
  { code: "02", name: "South Karelia" },
  { code: "03", name: "Southern Ostrobothnia" },
  { code: "04", name: "Southern Savonia" },
  { code: "05", name: "Kainuu" },
  { code: "06", name: "Tavastia Proper" },
  { code: "07", name: "Central Ostrobothnia" },
  { code: "08", name: "Central Finland" },
  { code: "09", name: "Kymenlaakso" },
  { code: "10", name: "Lapland" },
  { code: "11", name: "Pirkanmaa" },
  { code: "12", name: "Ostrobothnia" },
  { code: "13", name: "North Karelia" },
  { code: "14", name: "Northern Ostrobothnia" },
  { code: "15", name: "Northern Savonia" },
  { code: "16", name: "Päijänne Tavastia" },
  { code: "17", name: "Satakunta" },
  { code: "18", name: "Uusimaa" },
  { code: "19", name: "Southwest Finland" },
];

const CZ_REGIONS: Subdivision[] = [
  { code: "PR", name: "Prague" },
  { code: "ST", name: "Central Bohemian" },
  { code: "JC", name: "South Bohemian" },
  { code: "PL", name: "Plzeň" },
  { code: "KA", name: "Karlovy Vary" },
  { code: "US", name: "Ústí nad Labem" },
  { code: "LI", name: "Liberec" },
  { code: "KR", name: "Hradec Králové" },
  { code: "PA", name: "Pardubice" },
  { code: "VY", name: "Vysočina" },
  { code: "JM", name: "South Moravian" },
  { code: "OL", name: "Olomouc" },
  { code: "ZL", name: "Zlín" },
  { code: "MO", name: "Moravian-Silesian" },
];

const IL_DISTRICTS: Subdivision[] = [
  { code: "D", name: "Southern District" },
  { code: "HA", name: "Haifa" },
  { code: "JM", name: "Jerusalem" },
  { code: "M", name: "Central District" },
  { code: "TA", name: "Tel Aviv" },
  { code: "Z", name: "Northern District" },
];

const TW_REGIONS: Subdivision[] = [
  { code: "TPE", name: "Taipei" },
  { code: "NTP", name: "New Taipei" },
  { code: "TYN", name: "Taoyuan" },
  { code: "TXG", name: "Taichung" },
  { code: "TNN", name: "Tainan" },
  { code: "KHH", name: "Kaohsiung" },
  { code: "HSH", name: "Hsinchu" },
  { code: "KEE", name: "Keelung" },
  { code: "CYI", name: "Chiayi" },
  { code: "Other", name: "Other county / city" },
];

const HK_DISTRICTS: Subdivision[] = [
  { code: "HK", name: "Hong Kong Island" },
  { code: "KLN", name: "Kowloon" },
  { code: "NT", name: "New Territories" },
];

const SG_REGIONS: Subdivision[] = [
  { code: "Central", name: "Central" },
  { code: "East", name: "East" },
  { code: "North", name: "North" },
  { code: "North-East", name: "North-East" },
  { code: "West", name: "West" },
];

const PR_REGIONS: Subdivision[] = [
  { code: "San Juan", name: "San Juan" },
  { code: "Bayamón", name: "Bayamón" },
  { code: "Carolina", name: "Carolina" },
  { code: "Ponce", name: "Ponce" },
  { code: "Caguas", name: "Caguas" },
  { code: "Other", name: "Other municipality" },
];

/** Country code → subdivisions used in the checkout state/province select. */
export const COUNTRY_SUBDIVISIONS: Record<string, readonly Subdivision[]> = {
  US: US_STATES,
  CA: CA_PROVINCES,
  AU: AU_STATES,
  GB: GB_REGIONS,
  MX: MX_STATES,
  BR: BR_STATES,
  IN: IN_STATES,
  DE: DE_STATES,
  JP: JP_PREFECTURES,
  NZ: NZ_REGIONS,
  IE: IE_COUNTIES,
  ZA: ZA_PROVINCES,
  PH: PH_REGIONS,
  ES: ES_REGIONS,
  IT: IT_REGIONS,
  FR: FR_REGIONS,
  NL: NL_PROVINCES,
  BE: BE_REGIONS,
  CH: CH_CANTONS,
  AT: AT_STATES,
  AR: AR_PROVINCES,
  CL: CL_REGIONS,
  CO: CO_DEPARTMENTS,
  AE: AE_EMIRATES,
  KR: KR_REGIONS,
  MY: MY_STATES,
  TH: TH_REGIONS,
  ID: ID_PROVINCES,
  PT: PT_DISTRICTS,
  PL: PL_VOIVODESHIPS,
  SE: SE_COUNTIES,
  NO: NO_COUNTIES,
  DK: DK_REGIONS,
  FI: FI_REGIONS,
  CZ: CZ_REGIONS,
  IL: IL_DISTRICTS,
  TW: TW_REGIONS,
  HK: HK_DISTRICTS,
  SG: SG_REGIONS,
  PR: PR_REGIONS,
};

const SUBDIVISION_LABELS: Record<string, string> = {
  US: "State",
  CA: "Province / territory",
  AU: "State / territory",
  GB: "Country / region",
  MX: "State",
  BR: "State",
  IN: "State / territory",
  DE: "State",
  JP: "Prefecture",
  NZ: "Region",
  IE: "County",
  ZA: "Province",
  PH: "Region",
  ES: "Autonomous community",
  IT: "Region",
  FR: "Region",
  NL: "Province",
  BE: "Region",
  CH: "Canton",
  AT: "State",
  AR: "Province",
  CL: "Region",
  CO: "Department",
  AE: "Emirate",
  KR: "Region",
  MY: "State / territory",
  TH: "Region",
  ID: "Province",
  PT: "District",
  PL: "Voivodeship",
  SE: "County",
  NO: "County",
  DK: "Region",
  FI: "Region",
  CZ: "Region",
  IL: "District",
  TW: "City / county",
  HK: "Region",
  SG: "Region",
  PR: "Municipality",
};

export function getCountrySubdivisions(countryCode: string): readonly Subdivision[] | null {
  const list = COUNTRY_SUBDIVISIONS[countryCode.toUpperCase()];
  return list?.length ? list : null;
}

export function subdivisionFieldLabel(countryCode: string): string {
  return SUBDIVISION_LABELS[countryCode.toUpperCase()] ?? "State / province / region";
}

export function defaultSubdivisionForCountry(countryCode: string, preferred?: string): string {
  const list = getCountrySubdivisions(countryCode);
  if (!list) return preferred?.trim() || "";
  if (preferred) {
    const match = list.find(
      (s) =>
        s.code.toUpperCase() === preferred.trim().toUpperCase() ||
        s.name.toUpperCase() === preferred.trim().toUpperCase()
    );
    if (match) return match.code;
  }
  if (countryCode.toUpperCase() === "US") {
    const ca = list.find((s) => s.code === "CA");
    if (ca) return ca.code;
  }
  return list[0]?.code ?? "";
}

export function isValidSubdivision(countryCode: string, value: string): boolean {
  const list = getCountrySubdivisions(countryCode);
  if (!list) return value.trim().length > 0;
  const raw = value.trim().toUpperCase();
  return list.some((s) => s.code.toUpperCase() === raw || s.name.toUpperCase() === raw);
}
